### ISSUE TITLE
Button backlight timeout setting crashes

### ISSUE THREAD

**Issue by hoaysly** [Evolution-X/packages_apps_Evolution#549]
```kotlin
time: 1703114404237
msg: java.lang.ClassNotFoundException: com.evolution.settings.preference.BacklightTimeoutSeekBar
stacktrace: android.view.InflateException: Binary XML file line #107 in com.android.settings:layout/button_backlight: Binary XML file line #107 in com.android.settings:layout/button_backlight: Error inflating class com.evolution.settings.preference.BacklightTimeoutSeekBar
Caused by: android.view.InflateException: Binary XML file line #107 in com.android.settings:layout/button_backlight: Error inflating class com.evolution.settings.preference.BacklightTimeoutSeekBar
Caused by: java.lang.ClassNotFoundException: com.evolution.settings.preference.BacklightTimeoutSeekBar
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at android.view.LayoutInflater.createView(LayoutInflater.java:827)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1018)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1135)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:694)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at androidx.preference.PreferenceDialogFragmentCompat.onCreateDialogView(PreferenceDialogFragmentCompat.java:248)
	at com.evolution.settings.preference.CustomDialogPreference$CustomPreferenceDialogFragment.onCreateDialogView(CustomDialogPreference.java:210)
	at androidx.preference.PreferenceDialogFragmentCompat.onCreateDialog(PreferenceDialogFragmentCompat.java:148)
	at com.evolution.settings.preference.CustomDialogPreference$CustomPreferenceDialogFragment.onCreateDialog(CustomDialogPreference.java:201)
	at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:910)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:824)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1751)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:527)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1938)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1841)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1778)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:564)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8237)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:554)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.ClassNotFoundException: com.evolution.settings.preference.BacklightTimeoutSeekBar
	... 33 more

```

**Comment by hoaysly** [comment]
It looks like you overlooked modifying the class path in button_backlight.xml

**Comment by joeyhuab** [comment]
https://github.com/Evolution-X/packages_apps_Evolver/commit/592a7a9690aa8d566c7f2e2a9660bedf9f080090

fixed here
